apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base

replicas:
  - name: demo-nginx
    count: 4

images:
  - name: nginx
    newName: nginx
    newTag: 1.27-alpine
